### ISSUE TITLE
[PR] Allow to change internal batch size to run on GPU with low-VRAM

### ISSUE THREAD

**Issue by aleksusklim** [ai-forever/KandiSuperRes#2]
My fork ready to be merged:
https://github.com/klimaleksus/fork-KandiSuperRes/tree/main
(https://github.com/klimaleksus/fork-KandiSuperRes/commit/43afea74379726d04cea4cb2a8437daffdd7b672)

This allows to set `view_batch_size` (default of 15 is retained) to lower VRAM requirements.
For example:
```python
sr_image = sr_pipe(lr_image,view_batch_size=4)
```
For 1024x1024 inputs KandiSuperRes can fit in:
- 12 Gb GPU with `view_batch_size=4`
- 8 Gb GPU with `view_batch_size=2`
- 6 Gb GPU with `view_batch_size=1`

Other available arguments are `steps` (default is 5 and was configurable already) and `seed` (default is 0 and now can be changed too)

---

```python
class KandiSuperResPipeline:
…
    def __call__(
        self, 
        pil_image: PIL.Image.Image = None,
        steps: int = 5
    ) -> PIL.Image.Image:
…
        sr_image = base_diffusion.generate_panorama(height, width, self.device, self.dtype, steps, 
                                                   self.unet, lowres_img=lr_image, 
                                                   view_batch_size=15, eta=0.0, seed=0)
```

↓

```python
class KandiSuperResPipeline:
…
    def __call__(
        self, 
        pil_image: PIL.Image.Image = None,
        steps: int = 5,
        view_batch_size: int = 15,
        seed: int = 0
    ) -> PIL.Image.Image:
…
        sr_image = base_diffusion.generate_panorama(height, width, self.device, self.dtype, steps, 
                                                   self.unet, lowres_img=lr_image, 
                                                   view_batch_size=view_batch_size, eta=0.0, seed=seed)
```

**Comment by NastyaMittseva** [comment]
Thanks for your changes. Can you create a pull request?

**Comment by aleksusklim** [comment]
I tried and it said "only for collaborators" (I actually don't know how to enable PR-restrictions in GitHub for a repo), but this is not the first time it fails for me.
And the error is visible at the very last moment when I already prepared everything!
